import { Endpoints, WSPayload } from "./interopTypes";
import {
  ParamsType,
  randomPick,
  ReqType,
  ResType,
  sleep,
  withParameters,
} from "./utils";
import {
  BoardPoint,
  CityName,
  CurrentState,
  GameState,
  Player,
  PlayerColors,
  PlayerID,
  WinningState,
} from "./gameStateTypes";
import {
  isSegmentReachable,
  canPerformAction,
  generateGameID,
  createPlayer,
  generatePlayerID,
} from "./gameRules";
import { playerColorsArray, maxPenalityPoints } from "./config";
import {
  cities,
  City,
  CityColors,
  cityColorsArray,
  pointPairs,
  points,
} from "./map";
import { initialGameState, gameStateReducer } from "./gameStateManagement";
import {
  addPlayer,
  GameStateAction,
  placeRail,
  removePlayer,
  setPlayerInitialPoint,
  setState,
  startGame,
} from "./gameStateActions";

export {
  addPlayer,
  BoardPoint,
  canPerformAction,
  cities,
  City,
  CityColors,
  cityColorsArray,
  CityName,
  createPlayer,
  CurrentState,
  Endpoints,
  GameState,
  GameStateAction,
  gameStateReducer,
  generateGameID,
  generatePlayerID,
  initialGameState,
  isSegmentReachable,
  maxPenalityPoints,
  ParamsType,
  placeRail,
  Player,
  PlayerColors,
  playerColorsArray,
  PlayerID,
  pointPairs,
  points,
  randomPick,
  removePlayer,
  ReqType,
  ResType,
  setPlayerInitialPoint,
  setState,
  sleep,
  startGame,
  WinningState,
  withParameters,
  WSPayload,
};
